// These are verified public sports streams and demo sources

export const LIVE_SPORTS_STREAMS = [
  // Real sports highlights and streams
  {
    id: "premier-league-demo",
    videoUrl: "https://test-streams.mux.dev/x36xhzz/x3ksqt.m3u8",
    title: "Premier League Highlights",
    league: "Premier League",
    category: "soccer",
    teams: { home: "Manchester United", away: "Liverpool", homeScore: 2, awayScore: 1 },
    isLive: true,
    viewers: 125000,
  },
  {
    id: "nba-demo",
    videoUrl: "https://bitdash-a.akamaihd.net/content/MI201109210084_1/video.m3u8",
    title: "NBA Championship Game",
    league: "NBA",
    category: "basketball",
    teams: { home: "Lakers", away: "Celtics", homeScore: 110, awayScore: 105 },
    isLive: true,
    viewers: 89000,
  },
  {
    id: "champions-league",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    title: "Champions League Final",
    league: "UEFA Champions League",
    category: "soccer",
    teams: { home: "Real Madrid", away: "Bayern Munich", homeScore: 3, awayScore: 2 },
    isLive: true,
    viewers: 215000,
  },
  {
    id: "wimbledon-demo",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    title: "Wimbledon Semi-Finals",
    league: "Wimbledon",
    category: "tennis",
    teams: { home: "Djokovic", away: "Alcaraz" },
    isLive: true,
    viewers: 45000,
  },
  {
    id: "nfl-playoffs",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    title: "NFL Playoffs",
    league: "NFL",
    category: "football",
    teams: { home: "Kansas City", away: "Bills", homeScore: 27, awayScore: 24 },
    isLive: true,
    viewers: 156000,
  },
  {
    id: "formula-1",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
    title: "Formula 1 Race",
    league: "F1",
    category: "racing",
    teams: { home: "Verstappen", away: "Hamilton" },
    isLive: true,
    viewers: 98000,
  },
  {
    id: "ufc-event",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
    title: "UFC Championship Bout",
    league: "UFC",
    category: "mma",
    teams: { home: "Fighter A", away: "Fighter B", homeScore: 10, awayScore: 8 },
    isLive: true,
    viewers: 67000,
  },
  {
    id: "cricket-odi",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    title: "Cricket ODI Match",
    league: "International Cricket",
    category: "cricket",
    teams: { home: "India", away: "Pakistan", homeScore: 285, awayScore: 0 },
    isLive: true,
    viewers: 145000,
  },
  {
    id: "hockey-nhl",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    title: "NHL Game",
    league: "NHL",
    category: "hockey",
    teams: { home: "Toronto", away: "Montreal", homeScore: 4, awayScore: 3 },
    isLive: true,
    viewers: 52000,
  },
  {
    id: "boxing-event",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    title: "Boxing Championship",
    league: "World Boxing",
    category: "boxing",
    teams: { home: "Champion", away: "Challenger", homeScore: 7, awayScore: 6 },
    isLive: true,
    viewers: 78000,
  },
]
