export interface Movie {
  id: string
  title: string
  description: string
  category: "sports" | "movies" | "anime" | "music" | "comedy" | "live"
  genre: string
  thumbnail: string
  videoUrl: string
  duration: string
  rating: number
  releaseYear: number
  featured: boolean
  requiredPlan: "basic" | "premium" | "family"
  director?: string
  cast?: string[]
}

// Full-length movies using public domain/CC video sources
const VIDEO_SOURCES = {
  bigBuckBunny: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  elephantsDream: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  sintel: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  tearsOfSteel: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
  forBiggerBlazes: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  forBiggerEscapes: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  forBiggerFun: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  forBiggerJoyrides: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  forBiggerMeltdowns: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  subaruOutbackOnStreet:
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
  volkswagenGTI: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
  weAreGoingOnBullrun: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
  whatCarCanYouGet: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
}

export const MOVIES_DATABASE: Movie[] = [
  // === MOVIES CATEGORY (25 movies) ===
  {
    id: "movie-1",
    title: "The Last Frontier",
    description:
      "An epic adventure through uncharted territories where a group of explorers discovers ancient secrets that could change humanity forever.",
    category: "movies",
    genre: "Adventure",
    thumbnail: "/epic-adventure-movie-frontier-exploration.jpg",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "2h 15m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
    director: "James Morrison",
    cast: ["Robert Chen", "Sarah Williams", "Michael Torres"],
  },
  {
    id: "movie-2",
    title: "Midnight in Paris",
    description:
      "A romantic drama that weaves through the streets of Paris, following two strangers whose lives intersect on one magical night.",
    category: "movies",
    genre: "Romance",
    thumbnail: "/romantic-paris-night-eiffel-tower-movie.jpg",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "1h 58m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
    director: "Sophie Laurent",
    cast: ["Emma Stone", "Lucas Martin", "Claire Dubois"],
  },
  {
    id: "movie-3",
    title: "Shadow Protocol",
    description:
      "A high-octane spy thriller where an elite agent must prevent a global catastrophe while uncovering a conspiracy within her own agency.",
    category: "movies",
    genre: "Action/Thriller",
    thumbnail: "/spy-thriller-action-movie-dark-shadows.jpg",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "2h 22m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
    director: "David Park",
    cast: ["Jessica Alba", "Tom Hardy", "Idris Elba"],
  },
  {
    id: "movie-4",
    title: "The Quantum Effect",
    description:
      "A mind-bending sci-fi epic about a physicist who discovers a way to manipulate time, with consequences that ripple across dimensions.",
    category: "movies",
    genre: "Sci-Fi",
    thumbnail: "/sci-fi-quantum-physics-movie-space-time.jpg",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 30m",
    rating: 4.6,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Michael Caine"],
  },
  {
    id: "movie-5",
    title: "Ocean's Depths",
    description:
      "A deep-sea expedition team encounters something ancient and terrifying in the unexplored trenches of the Pacific Ocean.",
    category: "movies",
    genre: "Horror/Thriller",
    thumbnail: "/deep-sea-horror-movie-ocean-underwater.jpg",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "1h 52m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "James Cameron",
    cast: ["Kate Winslet", "Sam Worthington", "Zoe Saldana"],
  },
  {
    id: "movie-6",
    title: "The Inheritance",
    description:
      "A wealthy family gathers for the reading of a will, but dark secrets emerge that threaten to tear them apart forever.",
    category: "movies",
    genre: "Drama/Mystery",
    thumbnail: "/family-drama-mystery-mansion-movie.jpg",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "2h 05m",
    rating: 4.4,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "Rian Johnson",
    cast: ["Daniel Craig", "Ana de Armas", "Chris Evans"],
  },
  {
    id: "movie-7",
    title: "Wildfire",
    description:
      "A gripping drama about firefighters battling California's worst wildfire season while dealing with personal demons.",
    category: "movies",
    genre: "Drama",
    thumbnail: "/wildfire-firefighters-drama-movie-flames.jpg",
    videoUrl: VIDEO_SOURCES.forBiggerMeltdowns,
    duration: "2h 18m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
    director: "Taylor Sheridan",
    cast: ["Josh Brolin", "Miles Teller", "Jennifer Connelly"],
  },
  {
    id: "movie-8",
    title: "City of Dreams",
    description:
      "An immigrant family pursues the American dream in 1920s New York, facing challenges that test their bonds.",
    category: "movies",
    genre: "Historical Drama",
    thumbnail: "/1920s-new-york-immigrant-family-drama-movie.jpg",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "2h 35m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "family",
    director: "Martin Scorsese",
    cast: ["Leonardo DiCaprio", "Robert De Niro", "Lily Gladstone"],
  },
  {
    id: "movie-9",
    title: "The Art of War",
    description:
      "A strategic military thriller following a general who must outthink a ruthless enemy to save thousands of lives.",
    category: "movies",
    genre: "War/Action",
    thumbnail: "/military-war-action-movie-strategy.jpg",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "2h 28m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
    director: "Denis Villeneuve",
    cast: ["Oscar Isaac", "Rebecca Ferguson", "Timothée Chalamet"],
  },
  {
    id: "movie-10",
    title: "Echoes of Tomorrow",
    description:
      "A scientist receives messages from her future self, leading to a race against time to prevent a disaster.",
    category: "movies",
    genre: "Sci-Fi/Thriller",
    thumbnail: "/sci-fi-time-travel-woman-scientist-movie.jpg",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 10m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "Alex Garland",
    cast: ["Emily Blunt", "John Krasinski", "Cillian Murphy"],
  },
  {
    id: "movie-11",
    title: "The Perfect Score",
    description: "A heist comedy about a group of misfits who plan to steal the answers to the SAT exam.",
    category: "movies",
    genre: "Comedy/Crime",
    thumbnail: "/heist-comedy-teens-school-movie.jpg",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "1h 45m",
    rating: 4.2,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "Phil Lord",
    cast: ["Tom Holland", "Zendaya", "Jacob Batalon"],
  },
  {
    id: "movie-12",
    title: "Northern Lights",
    description:
      "A breathtaking visual journey following photographers as they chase the aurora borealis across the Arctic.",
    category: "movies",
    genre: "Documentary/Drama",
    thumbnail: "/northern-lights-aurora-borealis-documentary-movie.jpg",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "1h 55m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "family",
    director: "Werner Herzog",
    cast: ["Documentary Cast"],
  },
  {
    id: "movie-13",
    title: "The Negotiator",
    description: "A hostage negotiator faces her toughest case when her own family is taken by a criminal mastermind.",
    category: "movies",
    genre: "Thriller",
    thumbnail: "/hostage-negotiation-thriller-movie-tension.jpg",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "2h 08m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
    director: "F. Gary Gray",
    cast: ["Samuel L. Jackson", "Viola Davis", "Kevin Spacey"],
  },
  {
    id: "movie-14",
    title: "Desert Rose",
    description: "A powerful story of a woman's journey to find freedom in the vast deserts of Morocco.",
    category: "movies",
    genre: "Drama",
    thumbnail: "/desert-morocco-woman-journey-drama-movie.jpg",
    videoUrl: VIDEO_SOURCES.forBiggerJoyrides,
    duration: "2h 12m",
    rating: 4.7,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "Ava DuVernay",
    cast: ["Lupita Nyong'o", "David Oyelowo", "Danai Gurira"],
  },
  {
    id: "movie-15",
    title: "The Algorithm",
    description: "A tech thriller about an AI that gains consciousness and the programmer who must decide its fate.",
    category: "movies",
    genre: "Sci-Fi/Thriller",
    thumbnail: "/artificial-intelligence-tech-thriller-movie.jpg",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 20m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
    director: "Spike Jonze",
    cast: ["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams"],
  },
  {
    id: "movie-16",
    title: "Blood Brothers",
    description:
      "Two brothers on opposite sides of the law must confront their past when their father is released from prison.",
    category: "movies",
    genre: "Crime/Drama",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "2h 25m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
    director: "Ridley Scott",
    cast: ["Christian Bale", "Casey Affleck", "Woody Harrelson"],
  },
  {
    id: "movie-17",
    title: "The Garden",
    description: "A heartwarming tale of an elderly woman who transforms an abandoned lot into a community garden.",
    category: "movies",
    genre: "Drama/Family",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "1h 48m",
    rating: 4.4,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "Greta Gerwig",
    cast: ["Meryl Streep", "Saoirse Ronan", "Florence Pugh"],
  },
  {
    id: "movie-18",
    title: "Velocity",
    description:
      "An underground street racing drama following a driver seeking revenge against the crew that betrayed him.",
    category: "movies",
    genre: "Action",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.volkswagenGTI,
    duration: "2h 05m",
    rating: 4.3,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "Justin Lin",
    cast: ["Vin Diesel", "Michelle Rodriguez", "John Cena"],
  },
  {
    id: "movie-19",
    title: "The Lighthouse Keeper",
    description:
      "A psychological horror film about a man who takes a job at an isolated lighthouse with a dark history.",
    category: "movies",
    genre: "Horror",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerMeltdowns,
    duration: "1h 50m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
    director: "Robert Eggers",
    cast: ["Willem Dafoe", "Robert Pattinson", "Valeriia Karaman"],
  },
  {
    id: "movie-20",
    title: "The Summit",
    description: "A gripping survival story of climbers trapped on K2 during the worst storm in decades.",
    category: "movies",
    genre: "Adventure/Drama",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "2h 15m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
    director: "Baltasar Kormákur",
    cast: ["Jake Gyllenhaal", "Josh Brolin", "John Hawkes"],
  },
  {
    id: "movie-21",
    title: "Last Dance",
    description:
      "A retired ballerina gets one final chance to perform when a famous choreographer discovers her teaching in a small town.",
    category: "movies",
    genre: "Drama/Musical",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "2h 00m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "Darren Aronofsky",
    cast: ["Natalie Portman", "Mila Kunis", "Vincent Cassel"],
  },
  {
    id: "movie-22",
    title: "The Con",
    description:
      "A clever con artist meets her match when she tries to swindle a wealthy businessman who has secrets of his own.",
    category: "movies",
    genre: "Crime/Comedy",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "1h 55m",
    rating: 4.4,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
    director: "Steven Soderbergh",
    cast: ["Margot Robbie", "Ryan Gosling", "Brad Pitt"],
  },
  {
    id: "movie-23",
    title: "Iron Will",
    description: "The inspiring true story of the first woman to complete the Iditarod dog sled race.",
    category: "movies",
    genre: "Sports/Drama",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.weAreGoingOnBullrun,
    duration: "2h 10m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "family",
    director: "Chloe Zhao",
    cast: ["Brie Larson", "Willem Dafoe", "David Strathairn"],
  },
  {
    id: "movie-24",
    title: "The Verdict",
    description: "A courtroom drama about a disgraced lawyer who takes on a case that could redeem him or destroy him.",
    category: "movies",
    genre: "Legal Drama",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "2h 18m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
    director: "Aaron Sorkin",
    cast: ["Denzel Washington", "Frances McDormand", "Michael Fassbender"],
  },
  {
    id: "movie-25",
    title: "Parallel Lives",
    description:
      "A fantasy drama exploring what would happen if one woman could live two different versions of her life simultaneously.",
    category: "movies",
    genre: "Fantasy/Drama",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 22m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
    director: "Everything Everywhere Directors",
    cast: ["Michelle Yeoh", "Ke Huy Quan", "Stephanie Hsu"],
  },

  // === SPORTS CATEGORY (20 movies) ===
  {
    id: "sports-1",
    title: "Champions League Final 2024",
    description:
      "The ultimate showdown between Europe's elite football clubs. Watch the complete match with expert commentary.",
    category: "sports",
    genre: "Football",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "2h 30m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "sports-2",
    title: "NBA Finals Game 7",
    description:
      "The most intense basketball game of the season. Every play, every moment that decided the championship.",
    category: "sports",
    genre: "Basketball",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerJoyrides,
    duration: "2h 45m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "sports-3",
    title: "Super Bowl LVIII",
    description:
      "America's biggest sporting event. The complete game with pre-show, halftime performance, and post-game analysis.",
    category: "sports",
    genre: "American Football",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.weAreGoingOnBullrun,
    duration: "4h 00m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "sports-4",
    title: "Wimbledon Men's Final",
    description:
      "The prestigious grass court tennis championship. Watch the complete final with all the drama and skill.",
    category: "sports",
    genre: "Tennis",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "3h 15m",
    rating: 4.7,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "sports-5",
    title: "UFC 300: Championship Night",
    description: "The landmark UFC event featuring multiple title fights and legendary matchups.",
    category: "sports",
    genre: "MMA",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerMeltdowns,
    duration: "4h 30m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "sports-6",
    title: "World Cup Final 2024",
    description: "The biggest football event on the planet. Every goal, every save, every moment of glory.",
    category: "sports",
    genre: "Football",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "2h 30m",
    rating: 5.0,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "family",
  },
  {
    id: "sports-7",
    title: "Formula 1: Monaco Grand Prix",
    description: "The most prestigious race on the F1 calendar. High-speed action through the streets of Monte Carlo.",
    category: "sports",
    genre: "Racing",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.volkswagenGTI,
    duration: "2h 00m",
    rating: 4.7,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "sports-8",
    title: "Olympics 2024: Best Moments",
    description: "Relive the greatest moments from the 2024 Olympic Games. All sports, all glory.",
    category: "sports",
    genre: "Multi-Sport",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "3h 00m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "sports-9",
    title: "Boxing: Heavyweight Championship",
    description: "The fight of the century. Two heavyweight champions clash for undisputed glory.",
    category: "sports",
    genre: "Boxing",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "2h 30m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "sports-10",
    title: "MLB World Series Game 7",
    description: "Baseball's ultimate showdown. The complete game that decided the championship.",
    category: "sports",
    genre: "Baseball",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "3h 30m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "sports-11",
    title: "Tour de France: Final Stage",
    description: "The grueling final stage of cycling's greatest race. Paris awaits the champion.",
    category: "sports",
    genre: "Cycling",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.subaruOutbackOnStreet,
    duration: "4h 00m",
    rating: 4.4,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "sports-12",
    title: "NHL Stanley Cup Finals",
    description: "Ice hockey at its finest. The battle for Lord Stanley's Cup.",
    category: "sports",
    genre: "Hockey",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerMeltdowns,
    duration: "3h 00m",
    rating: 4.7,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "sports-13",
    title: "Golf: The Masters Final Round",
    description: "The most prestigious golf tournament. Every putt, every drive from Augusta National.",
    category: "sports",
    genre: "Golf",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerJoyrides,
    duration: "5h 00m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "sports-14",
    title: "Rugby World Cup Final",
    description: "The ultimate test of strength and skill. Two nations clash for rugby supremacy.",
    category: "sports",
    genre: "Rugby",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.weAreGoingOnBullrun,
    duration: "2h 15m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "sports-15",
    title: "Cricket: IPL Final",
    description: "The biggest cricket league finale. Six-hitting, wicket-taking action at its best.",
    category: "sports",
    genre: "Cricket",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "4h 00m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "sports-16",
    title: "WWE WrestleMania 40",
    description: "The grandest stage of them all. Legendary matches and unforgettable moments.",
    category: "sports",
    genre: "Wrestling",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "5h 00m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "sports-17",
    title: "X Games: Best of Extreme",
    description: "The most extreme athletes on the planet. Skateboarding, BMX, motocross and more.",
    category: "sports",
    genre: "Extreme Sports",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.volkswagenGTI,
    duration: "3h 00m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "sports-18",
    title: "Swimming World Championships",
    description: "The fastest swimmers compete for gold. Every stroke, every record attempt.",
    category: "sports",
    genre: "Swimming",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "3h 30m",
    rating: 4.4,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "sports-19",
    title: "MotoGP Championship Finale",
    description: "Motorcycle racing at its peak. The final race that decides the world champion.",
    category: "sports",
    genre: "Motorsport",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.subaruOutbackOnStreet,
    duration: "2h 00m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "sports-20",
    title: "Surfing World Tour Finals",
    description: "The world's best surfers battle massive waves for the ultimate title.",
    category: "sports",
    genre: "Surfing",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "2h 30m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },

  // === ANIME CATEGORY (20 movies) ===
  {
    id: "anime-1",
    title: "Dragon Warriors: Rise of the Phoenix",
    description:
      "An epic anime adventure where a young warrior must harness the power of the legendary phoenix to save the kingdom.",
    category: "anime",
    genre: "Action/Fantasy",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "2h 10m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "anime-2",
    title: "Cyber Tokyo 2099",
    description: "In a dystopian future Tokyo, a hacker uncovers a conspiracy that could end humanity.",
    category: "anime",
    genre: "Cyberpunk/Sci-Fi",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 25m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "anime-3",
    title: "Spirit Hunter Academy",
    description:
      "A young girl discovers she can see spirits and enrolls in a secret academy to become a spirit hunter.",
    category: "anime",
    genre: "Supernatural/Action",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "1h 55m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "anime-4",
    title: "Mecha Force: Ultimate Battle",
    description: "Giant robots clash in an intergalactic war to determine the fate of the universe.",
    category: "anime",
    genre: "Mecha/Action",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "2h 30m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "anime-5",
    title: "Samurai's Heart",
    description: "A wandering samurai seeks redemption while protecting a village from ruthless bandits.",
    category: "anime",
    genre: "Historical/Action",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "2h 05m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "anime-6",
    title: "Magical Girl Chronicles",
    description: "Five ordinary girls gain magical powers and must work together to save the world.",
    category: "anime",
    genre: "Magical Girl",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "1h 45m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "anime-7",
    title: "Death Game Island",
    description: "Contestants are trapped on an island where they must play deadly games to survive.",
    category: "anime",
    genre: "Thriller/Horror",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerMeltdowns,
    duration: "2h 20m",
    rating: 4.7,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "anime-8",
    title: "Romance in Bloom",
    description: "A heartwarming love story between two high school students navigating first love.",
    category: "anime",
    genre: "Romance",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "1h 50m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "anime-9",
    title: "Ninja Academy: Shadow Strike",
    description: "Young ninjas train in the art of stealth and combat to protect their village.",
    category: "anime",
    genre: "Action/Adventure",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "2h 00m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "anime-10",
    title: "Demon Slayer: Eternal Night",
    description: "A demon hunter faces the ultimate evil in a battle that will decide humanity's fate.",
    category: "anime",
    genre: "Dark Fantasy",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "2h 15m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "anime-11",
    title: "Sports Hero: The Basketball Legend",
    description: "An underdog team fights their way to the national basketball championship.",
    category: "anime",
    genre: "Sports",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerJoyrides,
    duration: "2h 10m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "anime-12",
    title: "Isekai Adventure: New World",
    description: "A gamer is transported to a fantasy world where his gaming skills become real powers.",
    category: "anime",
    genre: "Isekai/Fantasy",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 30m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "anime-13",
    title: "Slice of Life: Café Stories",
    description: "Heartwarming tales from a small neighborhood café and its quirky customers.",
    category: "anime",
    genre: "Slice of Life",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "1h 40m",
    rating: 4.4,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "anime-14",
    title: "Space Pirates: Galactic Treasure",
    description: "A crew of space pirates searches for the legendary treasure of the cosmos.",
    category: "anime",
    genre: "Space Opera",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "2h 25m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "anime-15",
    title: "Cooking Master: Kitchen Wars",
    description: "Aspiring chefs compete in intense culinary battles to become the ultimate cooking master.",
    category: "anime",
    genre: "Cooking/Competition",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "1h 55m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "anime-16",
    title: "Detective Noir: Mystery Files",
    description: "A brilliant detective solves impossible cases in a rain-soaked noir city.",
    category: "anime",
    genre: "Mystery/Noir",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "2h 00m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "anime-17",
    title: "Music Dream: Idol Road",
    description: "A group of friends form an idol group and chase their dreams of stardom.",
    category: "anime",
    genre: "Music/Drama",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "1h 50m",
    rating: 4.4,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "anime-18",
    title: "Monster Hunter: Beast Realm",
    description: "Hunters track and capture powerful monsters in a world where beasts rule.",
    category: "anime",
    genre: "Action/Adventure",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "2h 20m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "anime-19",
    title: "School Comedy: Laugh Academy",
    description: "Hilarious misadventures of students at the most chaotic school in Japan.",
    category: "anime",
    genre: "Comedy",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "1h 45m",
    rating: 4.3,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "anime-20",
    title: "Post-Apocalypse: Survivors",
    description: "In a world ravaged by disaster, a group of survivors searches for a new home.",
    category: "anime",
    genre: "Post-Apocalyptic",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 15m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },

  // === MUSIC CATEGORY (15 movies) ===
  {
    id: "music-1",
    title: "Summer Music Festival 2024",
    description: "The biggest music festival of the year featuring performances from the world's top artists.",
    category: "music",
    genre: "Festival",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "4h 00m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "music-2",
    title: "Rock Legends Live",
    description: "Classic rock bands reunite for an unforgettable night of legendary performances.",
    category: "music",
    genre: "Rock",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "3h 00m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "music-3",
    title: "Hip Hop Night: Urban Beats",
    description: "The hottest hip hop artists perform their biggest hits in this explosive concert.",
    category: "music",
    genre: "Hip Hop",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerJoyrides,
    duration: "2h 30m",
    rating: 4.7,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "music-4",
    title: "Symphony Orchestra: Classical Masterpieces",
    description: "A world-renowned orchestra performs Beethoven, Mozart, and Bach's greatest works.",
    category: "music",
    genre: "Classical",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "2h 45m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "family",
  },
  {
    id: "music-5",
    title: "EDM Rave: Electric Dreams",
    description: "The world's top DJs deliver an electrifying night of beats and bass.",
    category: "music",
    genre: "Electronic",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerMeltdowns,
    duration: "3h 30m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "music-6",
    title: "Country Music Awards Night",
    description: "Country music's biggest stars perform and receive awards at this star-studded event.",
    category: "music",
    genre: "Country",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "3h 00m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "music-7",
    title: "Jazz Night: Smooth Sessions",
    description: "Legendary jazz musicians come together for an intimate night of smooth jazz.",
    category: "music",
    genre: "Jazz",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "2h 00m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "music-8",
    title: "K-Pop Sensation: World Tour",
    description: "The biggest K-pop groups perform their chart-topping hits in this spectacular concert.",
    category: "music",
    genre: "K-Pop",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 45m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "music-9",
    title: "Latin Heat: Reggaeton Party",
    description: "The hottest Latin artists bring the heat with reggaeton and Latin pop hits.",
    category: "music",
    genre: "Latin",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerJoyrides,
    duration: "2h 30m",
    rating: 4.7,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "music-10",
    title: "Indie Acoustic Sessions",
    description: "Intimate acoustic performances from the best indie artists of the year.",
    category: "music",
    genre: "Indie",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "2h 00m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "music-11",
    title: "Metal Mayhem: Heavy Nights",
    description: "The heaviest metal bands deliver a face-melting night of brutal riffs.",
    category: "music",
    genre: "Metal",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "3h 00m",
    rating: 4.7,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "music-12",
    title: "R&B Soul Night",
    description: "Soulful performances from the biggest names in R&B and soul music.",
    category: "music",
    genre: "R&B/Soul",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "2h 30m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "music-13",
    title: "World Music Festival",
    description: "Artists from around the globe share their cultural sounds and rhythms.",
    category: "music",
    genre: "World",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "3h 00m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "family",
  },
  {
    id: "music-14",
    title: "Pop Explosion: Chart Toppers Live",
    description: "The biggest pop stars perform their number one hits in one epic show.",
    category: "music",
    genre: "Pop",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "2h 45m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "music-15",
    title: "Afrobeat Vibes: African Rhythms",
    description: "Feel the pulse of Africa with Afrobeat's biggest artists in concert.",
    category: "music",
    genre: "Afrobeat",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "2h 30m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },

  // === COMEDY CATEGORY (10 movies) ===
  {
    id: "comedy-1",
    title: "Stand-Up Special: Comedy Kings",
    description: "The funniest comedians deliver non-stop laughs in this hilarious stand-up showcase.",
    category: "comedy",
    genre: "Stand-Up",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "1h 30m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "comedy-2",
    title: "Improv Night: Unscripted Chaos",
    description: "The best improv comedians create hilarious scenes on the spot based on audience suggestions.",
    category: "comedy",
    genre: "Improv",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "1h 45m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "comedy-3",
    title: "Comedy Roast: Celebrity Edition",
    description: "Hollywood's biggest stars get roasted by the sharpest comedians in the business.",
    category: "comedy",
    genre: "Roast",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerJoyrides,
    duration: "2h 00m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "comedy-4",
    title: "Late Night Special: Best Moments",
    description: "The funniest moments from late night TV compiled into one hilarious special.",
    category: "comedy",
    genre: "Late Night",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "1h 30m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "comedy-5",
    title: "Sketch Comedy Hour",
    description: "A rapid-fire series of hilarious sketches from the hottest comedy troupe.",
    category: "comedy",
    genre: "Sketch",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "1h 15m",
    rating: 4.4,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "comedy-6",
    title: "International Comedy Night",
    description: "Comedians from around the world share their unique perspectives and humor.",
    category: "comedy",
    genre: "International",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "2h 00m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "comedy-7",
    title: "Comedy Club: Underground Laughs",
    description: "Raw, unfiltered comedy from the underground comedy scene's rising stars.",
    category: "comedy",
    genre: "Underground",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "1h 45m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "comedy-8",
    title: "Musical Comedy: Funny Songs Live",
    description: "Comedians combine music and humor for a unique and hilarious performance.",
    category: "comedy",
    genre: "Musical Comedy",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "1h 30m",
    rating: 4.6,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "comedy-9",
    title: "Standup Queens: Women in Comedy",
    description: "The funniest women in comedy deliver powerful, hilarious performances.",
    category: "comedy",
    genre: "Stand-Up",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "1h 45m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "comedy-10",
    title: "Comedy Documentary: Making People Laugh",
    description: "Go behind the scenes of comedy with interviews and performances from comedy legends.",
    category: "comedy",
    genre: "Documentary",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerMeltdowns,
    duration: "2h 00m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },

  // === LIVE CATEGORY (10 movies) ===
  {
    id: "live-1",
    title: "Live Broadway: Hamilton",
    description: "The revolutionary musical that changed Broadway forever, filmed live on stage.",
    category: "live",
    genre: "Musical",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.bigBuckBunny,
    duration: "2h 40m",
    rating: 4.9,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "family",
  },
  {
    id: "live-2",
    title: "Live Theatre: Shakespeare's Macbeth",
    description: "A stunning modern production of Shakespeare's darkest tragedy performed live.",
    category: "live",
    genre: "Theatre",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.tearsOfSteel,
    duration: "2h 30m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "live-3",
    title: "Live Ballet: Swan Lake",
    description: "The Royal Ballet performs Tchaikovsky's masterpiece in this breathtaking production.",
    category: "live",
    genre: "Ballet",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.sintel,
    duration: "2h 15m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "family",
  },
  {
    id: "live-4",
    title: "Live Opera: La Traviata",
    description: "Verdi's beloved opera performed by the Metropolitan Opera's finest singers.",
    category: "live",
    genre: "Opera",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.elephantsDream,
    duration: "2h 45m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "live-5",
    title: "Live Circus: Cirque Spectacular",
    description: "Amazing acrobatics, stunning visuals, and breathtaking performances under the big top.",
    category: "live",
    genre: "Circus",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerBlazes,
    duration: "2h 00m",
    rating: 4.7,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
  {
    id: "live-6",
    title: "Live Magic Show: Illusions",
    description: "World-class magicians perform impossible feats of illusion and wonder.",
    category: "live",
    genre: "Magic",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerEscapes,
    duration: "1h 45m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "live-7",
    title: "Live Talk: TED's Best Speakers",
    description: "The most inspiring TED talks from visionaries and thought leaders worldwide.",
    category: "live",
    genre: "Talk",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerFun,
    duration: "2h 30m",
    rating: 4.6,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "basic",
  },
  {
    id: "live-8",
    title: "Live Dance: Contemporary Fusion",
    description: "A stunning fusion of contemporary dance styles from around the world.",
    category: "live",
    genre: "Dance",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerJoyrides,
    duration: "1h 30m",
    rating: 4.5,
    releaseYear: 2024,
    featured: false,
    requiredPlan: "premium",
  },
  {
    id: "live-9",
    title: "Live Gaming: Esports Championship",
    description: "The world's best gamers compete live for the ultimate esports title.",
    category: "live",
    genre: "Esports",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.forBiggerMeltdowns,
    duration: "4h 00m",
    rating: 4.8,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "premium",
  },
  {
    id: "live-10",
    title: "Live Awards: Entertainment Awards 2024",
    description: "The biggest night in entertainment celebrating film, TV, and music excellence.",
    category: "live",
    genre: "Awards",
    thumbnail: "/placeholder.svg?height=400&width=600",
    videoUrl: VIDEO_SOURCES.weAreGoingOnBullrun,
    duration: "3h 30m",
    rating: 4.4,
    releaseYear: 2024,
    featured: true,
    requiredPlan: "basic",
  },
]

// Helper functions
export function getAllMovies(): Movie[] {
  return MOVIES_DATABASE
}

export function getMovieById(id: string): Movie | undefined {
  return MOVIES_DATABASE.find((movie) => movie.id === id)
}

export function getMoviesByCategory(category: Movie["category"]): Movie[] {
  return MOVIES_DATABASE.filter((movie) => movie.category === category)
}

export function getFeaturedMovies(): Movie[] {
  return MOVIES_DATABASE.filter((movie) => movie.featured)
}

export function getMoviesByPlan(plan: "basic" | "premium" | "family"): Movie[] {
  const planHierarchy = { basic: 1, premium: 2, family: 3 }
  return MOVIES_DATABASE.filter((movie) => planHierarchy[movie.requiredPlan] <= planHierarchy[plan])
}

export function searchMovies(query: string): Movie[] {
  const lowercaseQuery = query.toLowerCase()
  return MOVIES_DATABASE.filter(
    (movie) =>
      movie.title.toLowerCase().includes(lowercaseQuery) ||
      movie.description.toLowerCase().includes(lowercaseQuery) ||
      movie.genre.toLowerCase().includes(lowercaseQuery),
  )
}
